#@data/values
---
tap:
  ingress_domain: tap.example.com
  cnrs_subdomain: cnr.tap.example.com
container_registry:
  hostname: harbor.example.com
  username: admin
  password:
  repository: tap-wkld
workshop_git:
  username: user
  branch: main
tanzunet:
  username: user@example.com
  password:
gitops:
  https_repository_prefix: https://github.com/tsalm-pivotal
  basic_auth_username:
  basic_auth_password: 